set search_path to SITE_pcornet;

CREATE TABLE IF NOT EXISTS version_history (
	datetime TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	operation VARCHAR(100), 
	model VARCHAR(16), 
	model_version VARCHAR(50), 
	dms_version VARCHAR(50), 
	dmsa_version VARCHAR(50), 
	PRIMARY KEY (datetime)
);

INSERT INTO version_history (operation, model, model_version, dms_version, dmsa_version) VALUES ('create tables', 'pcornet', '6.0.0', '1.0.4-beta', '0.6.0');

CREATE TABLE condition (
	condition VARCHAR(18) NOT NULL, 
	condition_source VARCHAR(2) NOT NULL, 
	condition_status VARCHAR(2), 
	condition_type VARCHAR(2) NOT NULL, 
	conditionid VARCHAR(256) NOT NULL, 
	encounterid VARCHAR(256), 
	onset_date DATE, 
	patid VARCHAR(256) NOT NULL, 
	raw_condition VARCHAR(256), 
	raw_condition_source VARCHAR(256), 
	raw_condition_status VARCHAR(256), 
	raw_condition_type VARCHAR(256), 
	report_date DATE, 
	resolve_date DATE, 
	CONSTRAINT xpk_condition PRIMARY KEY (conditionid)
);

CREATE TABLE death (
	death_date DATE, 
	death_date_impute VARCHAR(2), 
	death_match_confidence VARCHAR(2), 
	death_source VARCHAR(2) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	CONSTRAINT xpk_death PRIMARY KEY (patid, death_source)
);

CREATE TABLE death_cause (
	death_cause VARCHAR(8) NOT NULL, 
	death_cause_code VARCHAR(2) NOT NULL, 
	death_cause_confidence VARCHAR(2), 
	death_cause_source VARCHAR(2) NOT NULL, 
	death_cause_type VARCHAR(2) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	CONSTRAINT xpk_death_cause PRIMARY KEY (patid, death_cause, death_cause_code, death_cause_type, death_cause_source)
);

CREATE TABLE demographic (
	biobank_flag VARCHAR(1), 
	birth_date DATE, 
	birth_time VARCHAR(5), 
	gender_identity VARCHAR(2), 
	hispanic VARCHAR(2), 
	pat_pref_language_spoken VARCHAR(3), 
	patid VARCHAR(256) NOT NULL, 
	race VARCHAR(2), 
	raw_gender_identity VARCHAR(256), 
	raw_hispanic VARCHAR(256), 
	raw_pat_pref_language_spoken VARCHAR(256), 
	raw_race VARCHAR(256), 
	raw_sex VARCHAR(256), 
	raw_sexual_orientation VARCHAR(256), 
	sex VARCHAR(2), 
	sexual_orientation VARCHAR(2), 
	CONSTRAINT xpk_demographic PRIMARY KEY (patid)
);

CREATE TABLE diagnosis (
	admit_date DATE, 
	diagnosisid VARCHAR(256) NOT NULL, 
	dx VARCHAR(18) NOT NULL, 
	dx_date DATE, 
	dx_origin VARCHAR(2), 
	dx_poa VARCHAR(2), 
	dx_source VARCHAR(2) NOT NULL, 
	dx_type VARCHAR(2) NOT NULL, 
	enc_type VARCHAR(2), 
	encounterid VARCHAR(256) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	pdx VARCHAR(2), 
	providerid VARCHAR(256), 
	raw_dx VARCHAR(256), 
	raw_dx_poa VARCHAR(256), 
	raw_dx_source VARCHAR(256), 
	raw_dx_type VARCHAR(256), 
	raw_pdx VARCHAR(256), 
	CONSTRAINT xpk_diagnosis PRIMARY KEY (diagnosisid)
);

CREATE TABLE dispensing (
	dispense_amt NUMERIC(15, 8), 
	dispense_date DATE NOT NULL, 
	dispense_dose_disp NUMERIC(15, 8), 
	dispense_dose_disp_unit VARCHAR(256), 
	dispense_route VARCHAR(256), 
	dispense_source VARCHAR(2), 
	dispense_sup NUMERIC(15, 8), 
	dispensingid VARCHAR(256) NOT NULL, 
	ndc VARCHAR(11) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	prescribingid VARCHAR(256), 
	raw_dispense_dose_disp VARCHAR(256), 
	raw_dispense_dose_disp_unit VARCHAR(256), 
	raw_dispense_route VARCHAR(256), 
	raw_ndc VARCHAR(256), 
	CONSTRAINT xpk_dispensing PRIMARY KEY (dispensingid)
);

CREATE TABLE encounter (
	admit_date DATE NOT NULL, 
	admit_time VARCHAR(5), 
	admitting_source VARCHAR(2), 
	discharge_date DATE, 
	discharge_disposition VARCHAR(2), 
	discharge_status VARCHAR(2), 
	discharge_time VARCHAR(5), 
	drg VARCHAR(3), 
	drg_type VARCHAR(2), 
	enc_type VARCHAR(2) NOT NULL, 
	encounterid VARCHAR(256) NOT NULL, 
	facility_location VARCHAR(5), 
	facility_type VARCHAR(256), 
	facilityid VARCHAR(256), 
	patid VARCHAR(256) NOT NULL, 
	payer_type_primary VARCHAR(5), 
	payer_type_secondary VARCHAR(5), 
	providerid VARCHAR(256), 
	raw_admitting_source VARCHAR(256), 
	raw_discharge_disposition VARCHAR(256), 
	raw_discharge_status VARCHAR(256), 
	raw_drg_type VARCHAR(256), 
	raw_enc_type VARCHAR(256), 
	raw_facility_type VARCHAR(256), 
	raw_payer_id_primary VARCHAR(256), 
	raw_payer_id_secondary VARCHAR(256), 
	raw_payer_name_primary VARCHAR(256), 
	raw_payer_name_secondary VARCHAR(256), 
	raw_payer_type_primary VARCHAR(256), 
	raw_payer_type_secondary VARCHAR(256), 
	raw_siteid VARCHAR(256), 
	CONSTRAINT xpk_encounter PRIMARY KEY (encounterid)
);

CREATE TABLE enrollment (
	chart VARCHAR(1), 
	enr_basis VARCHAR(1) NOT NULL, 
	enr_end_date DATE, 
	enr_start_date DATE NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	CONSTRAINT xpk_enrollment PRIMARY KEY (patid, enr_start_date, enr_basis)
);

CREATE TABLE harvest (
	address_period_end_mgmt VARCHAR(2), 
	address_period_start_mgmt VARCHAR(2), 
	admit_date_mgmt VARCHAR(2), 
	birth_date_mgmt VARCHAR(2), 
	cdm_version VARCHAR(3), 
	datamart_claims VARCHAR(2), 
	datamart_ehr VARCHAR(2), 
	datamart_name VARCHAR(20), 
	datamart_platform VARCHAR(2), 
	datamartid VARCHAR(10) NOT NULL, 
	death_date_mgmt VARCHAR(2), 
	discharge_date_mgmt VARCHAR(2), 
	dispense_date_mgmt VARCHAR(2), 
	dx_date_mgmt VARCHAR(2), 
	enr_end_date_mgmt VARCHAR(2), 
	enr_start_date_mgmt VARCHAR(2), 
	lab_order_date_mgmt VARCHAR(2), 
	measure_date_mgmt VARCHAR(2), 
	medadmin_start_date_mgmt VARCHAR(2), 
	medadmin_stop_date_mgmt VARCHAR(2), 
	network_name VARCHAR(20), 
	networkid VARCHAR(10) NOT NULL, 
	obsclin_start_date_mgmt VARCHAR(2), 
	obsclin_stop_date_mgmt VARCHAR(2), 
	obsgen_start_date_mgmt VARCHAR(2), 
	obsgen_stop_date_mgmt VARCHAR(2), 
	onset_date_mgmt VARCHAR(2), 
	pro_date_mgmt VARCHAR(2), 
	px_date_mgmt VARCHAR(2), 
	refresh_condition_date DATE, 
	refresh_death_cause_date DATE, 
	refresh_death_date DATE, 
	refresh_demographic_date DATE, 
	refresh_diagnosis_date DATE, 
	refresh_dispensing_date DATE, 
	refresh_encounter_date DATE, 
	refresh_enrollment_date DATE, 
	refresh_hash_token_date DATE, 
	refresh_immunization_date DATE, 
	refresh_lab_result_cm_date DATE, 
	refresh_lds_address_hx_date DATE, 
	refresh_med_admin_date DATE, 
	refresh_obs_clin_date DATE, 
	refresh_obs_gen_date DATE, 
	refresh_pcornet_trial_date DATE, 
	refresh_prescribing_date DATE, 
	refresh_pro_cm_date DATE, 
	refresh_procedures_date DATE, 
	refresh_provider_date DATE, 
	refresh_vital_date DATE, 
	report_date_mgmt VARCHAR(2), 
	resolve_date_mgmt VARCHAR(2), 
	result_date_mgmt VARCHAR(2), 
	rx_end_date_mgmt VARCHAR(2), 
	rx_order_date_mgmt VARCHAR(2), 
	rx_start_date_mgmt VARCHAR(2), 
	specimen_date_mgmt VARCHAR(2), 
	token_encryption_key VARCHAR(256), 
	vx_admin_date_mgmt VARCHAR(2), 
	vx_exp_date_mgmt VARCHAR(2), 
	vx_record_date_mgmt VARCHAR(2), 
	CONSTRAINT xpk_harvest PRIMARY KEY (networkid, datamartid)
);

CREATE TABLE hash_token (
	patid VARCHAR(256) NOT NULL, 
	token_01 VARCHAR(256), 
	token_02 VARCHAR(256), 
	token_03 VARCHAR(256), 
	token_04 VARCHAR(256), 
	token_05 VARCHAR(256), 
	token_16 VARCHAR(256), 
	CONSTRAINT xpk_hashtoken PRIMARY KEY (patid)
);

CREATE TABLE immunization (
	encounterid VARCHAR(256), 
	immunizationid VARCHAR(256) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	proceduresid VARCHAR(256), 
	raw_vx_body_site VARCHAR(256), 
	raw_vx_code VARCHAR(256), 
	raw_vx_code_type VARCHAR(256), 
	raw_vx_dose VARCHAR(256), 
	raw_vx_dose_unit VARCHAR(256), 
	raw_vx_manufacturer VARCHAR(256), 
	raw_vx_name VARCHAR(256), 
	raw_vx_route VARCHAR(256), 
	raw_vx_status VARCHAR(256), 
	raw_vx_status_reason VARCHAR(256), 
	vx_admin_date DATE, 
	vx_body_site VARCHAR(256), 
	vx_code VARCHAR(256) NOT NULL, 
	vx_code_type VARCHAR(2) NOT NULL, 
	vx_dose NUMERIC(20, 5), 
	vx_dose_unit VARCHAR(256), 
	vx_exp_date DATE, 
	vx_lot_num VARCHAR(256), 
	vx_manufacturer VARCHAR(256), 
	vx_providerid VARCHAR(256), 
	vx_record_date DATE, 
	vx_route VARCHAR(256), 
	vx_source VARCHAR(2), 
	vx_status VARCHAR(2) NOT NULL, 
	vx_status_reason VARCHAR(2), 
	CONSTRAINT xpk_immunization PRIMARY KEY (immunizationid)
);

CREATE TABLE lab_history (
	age_max_wks NUMERIC(20, 5), 
	age_min_wks NUMERIC(20, 5), 
	lab_facilityid VARCHAR(256), 
	lab_loinc VARCHAR(10) NOT NULL, 
	labhistoryid VARCHAR(256) NOT NULL, 
	norm_modifier_high VARCHAR(2), 
	norm_modifier_low VARCHAR(2), 
	norm_range_high VARCHAR(10), 
	norm_range_low VARCHAR(10), 
	period_end DATE, 
	period_start DATE, 
	race VARCHAR(2), 
	raw_lab_name VARCHAR(256), 
	raw_range VARCHAR(256), 
	raw_unit VARCHAR(256), 
	result_unit VARCHAR(256), 
	sex VARCHAR(2), 
	CONSTRAINT xpk_labhist PRIMARY KEY (labhistoryid)
);

CREATE TABLE lab_result_cm (
	abn_ind VARCHAR(2), 
	encounterid VARCHAR(256), 
	lab_loinc VARCHAR(10), 
	lab_loinc_source VARCHAR(2), 
	lab_order_date DATE, 
	lab_px VARCHAR(11), 
	lab_px_type VARCHAR(2), 
	lab_result_cm_id VARCHAR(256) NOT NULL, 
	lab_result_source VARCHAR(2), 
	norm_modifier_high VARCHAR(2), 
	norm_modifier_low VARCHAR(2), 
	norm_range_high VARCHAR(10), 
	norm_range_low VARCHAR(10), 
	patid VARCHAR(256) NOT NULL, 
	priority VARCHAR(2), 
	raw_facility_code VARCHAR(256), 
	raw_lab_code VARCHAR(256), 
	raw_lab_name VARCHAR(256), 
	raw_order_dept VARCHAR(256), 
	raw_panel VARCHAR(256), 
	raw_result VARCHAR(256), 
	raw_unit VARCHAR(256), 
	result_date DATE NOT NULL, 
	result_loc VARCHAR(2), 
	result_modifier VARCHAR(2), 
	result_num NUMERIC(15, 8), 
	result_qual VARCHAR(256), 
	result_snomed VARCHAR(256), 
	result_time VARCHAR(5), 
	result_unit VARCHAR(256), 
	specimen_date DATE, 
	specimen_source VARCHAR(256), 
	specimen_time VARCHAR(5), 
	CONSTRAINT xpk_lab_result_cm PRIMARY KEY (lab_result_cm_id)
);

CREATE TABLE lds_address_history (
	address_city VARCHAR(256), 
	address_period_end DATE, 
	address_period_start DATE, 
	address_preferred VARCHAR(2) NOT NULL, 
	address_state VARCHAR(2), 
	address_type VARCHAR(2) NOT NULL, 
	address_use VARCHAR(2) NOT NULL, 
	address_zip5 VARCHAR(5), 
	address_zip9 VARCHAR(9), 
	addressid VARCHAR(256) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	CONSTRAINT xpk_ldsaddhist PRIMARY KEY (addressid)
);

CREATE TABLE med_admin (
	encounterid VARCHAR(256), 
	medadmin_code VARCHAR(256), 
	medadmin_dose_admin NUMERIC(20, 5), 
	medadmin_dose_admin_unit VARCHAR(256), 
	medadmin_providerid VARCHAR(256), 
	medadmin_route VARCHAR(256), 
	medadmin_source VARCHAR(2), 
	medadmin_start_date DATE NOT NULL, 
	medadmin_start_time VARCHAR(5), 
	medadmin_stop_date DATE, 
	medadmin_stop_time VARCHAR(5), 
	medadmin_type VARCHAR(2), 
	medadminid VARCHAR(256) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	prescribingid VARCHAR(256), 
	raw_medadmin_code VARCHAR(256), 
	raw_medadmin_dose_admin VARCHAR(256), 
	raw_medadmin_dose_admin_unit VARCHAR(256), 
	raw_medadmin_med_name VARCHAR(256), 
	raw_medadmin_route VARCHAR(256), 
	CONSTRAINT xpk_medadminid PRIMARY KEY (medadminid)
);

CREATE TABLE obs_clin (
	encounterid VARCHAR(256), 
	obsclin_abn_ind VARCHAR(2), 
	obsclin_code VARCHAR(256), 
	obsclin_providerid VARCHAR(256), 
	obsclin_result_modifier VARCHAR(2), 
	obsclin_result_num NUMERIC(15, 8), 
	obsclin_result_qual VARCHAR(256), 
	obsclin_result_snomed VARCHAR(256), 
	obsclin_result_text VARCHAR(256), 
	obsclin_result_unit VARCHAR(256), 
	obsclin_source VARCHAR(2), 
	obsclin_start_date DATE NOT NULL, 
	obsclin_start_time VARCHAR(5), 
	obsclin_stop_date DATE, 
	obsclin_stop_time VARCHAR(5), 
	obsclin_type VARCHAR(2), 
	obsclinid VARCHAR(256) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	raw_obsclin_code VARCHAR(256), 
	raw_obsclin_modifier VARCHAR(256), 
	raw_obsclin_name VARCHAR(256), 
	raw_obsclin_result VARCHAR(256), 
	raw_obsclin_type VARCHAR(256), 
	raw_obsclin_unit VARCHAR(256), 
	CONSTRAINT xpk_obsclinid PRIMARY KEY (obsclinid)
);

CREATE TABLE obs_gen (
	encounterid VARCHAR(256), 
	obsgen_abn_ind VARCHAR(2), 
	obsgen_code VARCHAR(256), 
	obsgen_id_modified VARCHAR(256), 
	obsgen_providerid VARCHAR(256), 
	obsgen_result_modifier VARCHAR(2), 
	obsgen_result_num NUMERIC(15, 8), 
	obsgen_result_qual VARCHAR(256), 
	obsgen_result_text VARCHAR(256), 
	obsgen_result_unit VARCHAR(256), 
	obsgen_source VARCHAR(2), 
	obsgen_start_date DATE NOT NULL, 
	obsgen_start_time VARCHAR(5), 
	obsgen_stop_date DATE, 
	obsgen_stop_time VARCHAR(5), 
	obsgen_table_modified VARCHAR(3), 
	obsgen_type VARCHAR(30), 
	obsgenid VARCHAR(256) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	raw_obsgen_code VARCHAR(256), 
	raw_obsgen_name VARCHAR(256), 
	raw_obsgen_result VARCHAR(256), 
	raw_obsgen_type VARCHAR(256), 
	raw_obsgen_unit VARCHAR(256), 
	CONSTRAINT xpk_obsgenid PRIMARY KEY (obsgenid)
);

CREATE TABLE pcornet_trial (
	participantid VARCHAR(256) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	trial_end_date DATE, 
	trial_enroll_date DATE, 
	trial_invite_code VARCHAR(20), 
	trial_siteid VARCHAR(256), 
	trial_withdraw_date DATE, 
	trialid VARCHAR(20) NOT NULL, 
	CONSTRAINT xpk_pcornet_trial PRIMARY KEY (patid, trialid, participantid)
);

CREATE TABLE prescribing (
	encounterid VARCHAR(256), 
	patid VARCHAR(256) NOT NULL, 
	prescribingid VARCHAR(256) NOT NULL, 
	raw_rx_dose_ordered VARCHAR(256), 
	raw_rx_dose_ordered_unit VARCHAR(256), 
	raw_rx_frequency VARCHAR(256), 
	raw_rx_med_name VARCHAR(256), 
	raw_rx_ndc VARCHAR(256), 
	raw_rx_quantity VARCHAR(256), 
	raw_rx_refills VARCHAR(256), 
	raw_rx_route VARCHAR(256), 
	raw_rxnorm_cui VARCHAR(8), 
	rx_basis VARCHAR(2), 
	rx_days_supply NUMERIC(15, 8), 
	rx_dispense_as_written VARCHAR(2), 
	rx_dose_form VARCHAR(256), 
	rx_dose_ordered NUMERIC(15, 8), 
	rx_dose_ordered_unit VARCHAR(256), 
	rx_end_date DATE, 
	rx_frequency VARCHAR(2), 
	rx_order_date DATE, 
	rx_order_time VARCHAR(5), 
	rx_prn_flag VARCHAR(1), 
	rx_providerid VARCHAR(256), 
	rx_quantity NUMERIC(15, 8), 
	rx_refills NUMERIC(15, 8), 
	rx_route VARCHAR(256), 
	rx_source VARCHAR(2), 
	rx_start_date DATE, 
	rxnorm_cui VARCHAR(8), 
	CONSTRAINT xpk_prescribing PRIMARY KEY (prescribingid)
);

CREATE TABLE private_address_geocode (
	addressid VARCHAR(256) NOT NULL, 
	assignment_date DATE, 
	geo_accuracy VARCHAR(2), 
	geo_prov_ref VARCHAR(256), 
	geocode_block VARCHAR(256), 
	geocode_county VARCHAR(256), 
	geocode_custom VARCHAR(256), 
	geocode_custom_text VARCHAR(256), 
	geocode_group VARCHAR(256), 
	geocode_latitude VARCHAR(256), 
	geocode_longitude VARCHAR(256), 
	geocode_state VARCHAR(2), 
	geocode_tract VARCHAR(256), 
	geocode_zcta VARCHAR(256), 
	geocodeid VARCHAR(256) NOT NULL, 
	shapefile VARCHAR(256), 
	CONSTRAINT xpk_private_address_geo PRIMARY KEY (geocodeid)
);

CREATE TABLE private_address_history (
	address_city VARCHAR(256), 
	address_county VARCHAR(256), 
	address_detail VARCHAR(256), 
	address_period_end DATE, 
	address_period_start DATE, 
	address_preferred VARCHAR(2) NOT NULL, 
	address_state VARCHAR(2), 
	address_street VARCHAR(256), 
	address_type VARCHAR(2) NOT NULL, 
	address_use VARCHAR(2) NOT NULL, 
	address_zip5 VARCHAR(5), 
	address_zip9 VARCHAR(9), 
	addressid VARCHAR(256) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	raw_address_text VARCHAR(256), 
	CONSTRAINT xpk_private_address_hist PRIMARY KEY (addressid)
);

CREATE TABLE private_demographic (
	biobank_flag VARCHAR(1), 
	birth_date DATE, 
	birth_time VARCHAR(5), 
	gender_identity VARCHAR(2), 
	hispanic VARCHAR(2), 
	managing_org VARCHAR(256), 
	mrn VARCHAR(256), 
	org_patid VARCHAR(256), 
	pat_firstname VARCHAR(256) NOT NULL, 
	pat_lastname VARCHAR(256) NOT NULL, 
	pat_maidenname VARCHAR(256), 
	pat_middlename VARCHAR(256), 
	pat_pref_language_spoken VARCHAR(3), 
	pat_ssn VARCHAR(256), 
	patid VARCHAR(256) NOT NULL, 
	primary_email VARCHAR(256), 
	primary_phone VARCHAR(10), 
	race VARCHAR(2), 
	raw_gender_identity VARCHAR(256), 
	raw_hispanic VARCHAR(256), 
	raw_pat_name VARCHAR(256), 
	raw_pat_pref_language_spoken VARCHAR(256), 
	raw_race VARCHAR(256), 
	raw_sex VARCHAR(256), 
	raw_sexual_orientation VARCHAR(256), 
	sex VARCHAR(2), 
	sexual_orientation VARCHAR(2), 
	CONSTRAINT xpk_private_demographic PRIMARY KEY (patid)
);

CREATE TABLE pro_cm (
	encounterid VARCHAR(256), 
	patid VARCHAR(256) NOT NULL, 
	pro_cat VARCHAR(2), 
	pro_cm_id VARCHAR(256) NOT NULL, 
	pro_date DATE NOT NULL, 
	pro_item_fullname VARCHAR(256), 
	pro_item_loinc VARCHAR(10), 
	pro_item_name VARCHAR(256), 
	pro_item_text VARCHAR(256), 
	pro_item_version VARCHAR(256), 
	pro_measure_count_scored NUMERIC(15, 8), 
	pro_measure_fullname VARCHAR(256), 
	pro_measure_loinc VARCHAR(10), 
	pro_measure_name VARCHAR(256), 
	pro_measure_scaled_tscore NUMERIC(15, 8), 
	pro_measure_score NUMERIC(15, 8), 
	pro_measure_seq VARCHAR(256), 
	pro_measure_standard_error NUMERIC(15, 8), 
	pro_measure_theta NUMERIC(15, 8), 
	pro_measure_version VARCHAR(256), 
	pro_method VARCHAR(2), 
	pro_mode VARCHAR(2), 
	pro_response_num NUMERIC(15, 8), 
	pro_response_text VARCHAR(256), 
	pro_source VARCHAR(2), 
	pro_time VARCHAR(5), 
	pro_type VARCHAR(2), 
	CONSTRAINT xpk_pro_cm PRIMARY KEY (pro_cm_id)
);

CREATE TABLE procedures (
	admit_date DATE, 
	enc_type VARCHAR(2), 
	encounterid VARCHAR(256) NOT NULL, 
	patid VARCHAR(256) NOT NULL, 
	ppx VARCHAR(2), 
	proceduresid VARCHAR(256) NOT NULL, 
	providerid VARCHAR(256), 
	px VARCHAR(11) NOT NULL, 
	px_date DATE, 
	px_source VARCHAR(2), 
	px_type VARCHAR(2) NOT NULL, 
	raw_ppx VARCHAR(256), 
	raw_px VARCHAR(256), 
	raw_px_type VARCHAR(256), 
	CONSTRAINT xpk_procedures PRIMARY KEY (proceduresid)
);

CREATE TABLE provider (
	provider_npi NUMERIC(15, 8), 
	provider_npi_flag VARCHAR(1), 
	provider_sex VARCHAR(2), 
	provider_specialty_primary VARCHAR(256), 
	providerid VARCHAR(256) NOT NULL, 
	raw_provider_specialty_primary VARCHAR(256), 
	CONSTRAINT xpk_providerid PRIMARY KEY (providerid)
);

CREATE TABLE vital (
	bp_position VARCHAR(2), 
	diastolic NUMERIC(15, 8), 
	encounterid VARCHAR(256), 
	ht NUMERIC(15, 8), 
	measure_date DATE NOT NULL, 
	measure_time VARCHAR(5), 
	original_bmi NUMERIC(15, 8), 
	patid VARCHAR(256) NOT NULL, 
	raw_bp_position VARCHAR(256), 
	raw_diastolic VARCHAR(256), 
	raw_smoking VARCHAR(256), 
	raw_systolic VARCHAR(256), 
	raw_tobacco VARCHAR(256), 
	raw_tobacco_type VARCHAR(256), 
	smoking VARCHAR(2), 
	systolic NUMERIC(15, 8), 
	tobacco VARCHAR(2), 
	tobacco_type VARCHAR(2), 
	vital_source VARCHAR(2) NOT NULL, 
	vitalid VARCHAR(256) NOT NULL, 
	wt NUMERIC(15, 8), 
	CONSTRAINT xpk_vital PRIMARY KEY (vitalid)
);
