#!/bin/bash

export SCRIPTNAME="validate_pcornetcdm_to_pcornetcdm_load"

NOW=`date +%Y%m%d%H%M%S`

VALIDATEDATABASE=$DATABASE

LOGFILENAME="$SCRIPTNAME.$VALIDATEDATABASE.$NOW".log

echo "Beginning Execution of $SCRIPTNAME on $VALIDATEDATABASE at $NOW" >> log/"$LOGFILENAME"

SQLSTATEMENT="select count(1) from pcornet_cdm.demographic;"
echo "Validating Table 1" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"

SQLSTATEMENT="select count(1) from pcornet_cdm.enrollment;"
echo "Validating Table 2" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"

SQLSTATEMENT="select count(1) from pcornet_cdm.death;"
echo "Validating Table 3" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"

SQLSTATEMENT="select count(1) from pcornet_cdm.death_cause;"
echo "Validating Table 4" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"

SQLSTATEMENT="select count(1) from pcornet_cdm.encounter;"
echo "Validating Table 5" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"

SQLSTATEMENT="select count(1) from pcornet_cdm.condition;"
echo "Validating Table 6" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"

SQLSTATEMENT="select count(1) from pcornet_cdm.diagnosis;"
echo "Validating Table 7" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"

SQLSTATEMENT="select count(1) from pcornet_cdm.procedure;"
echo "Validating Table 8" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"

SQLSTATEMENT="select count(1) from pcornet_cdm.dispensing;"
echo "Validating Table 9" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"

SQLSTATEMENT="select count(1) from pcornet_cdm.prescribing;"
echo "Validating Table 10" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"

SQLSTATEMENT="select count(1) from pcornet_cdm.vital;"
echo "Validating Table 11" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"

SQLSTATEMENT="select count(1) from pcornet_cdm.lab_result_cm;"
echo "Validating Table 12" >> log/"$LOGFILENAME"
echo "$SQLSTATEMENT  :  " >> log/"$LOGFILENAME"
echo "$EXTRACTDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$EXTRACTDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
echo "$LOADDBHOSTNAME" >> log/"$LOGFILENAME"
PGPASSWORD="$ETL_DATABASE_USER_PASSWORD"  nohup time psql --host="$LOADDBHOSTNAME"   --user="$ETL_DATABASE_USER"  --dbname="$VALIDATEDATABASE" -c "$SQLSTATEMENT" >> log/"$LOGFILENAME"
printf "\n"
