begin;
drop table SITE_pcornet.ms;
drop table SITE_pcornet.ms_bmi;
drop table SITE_pcornet.ms_dia;
drop table SITE_pcornet.ms_sys;
drop table SITE_pcornet.ms_wt;
drop table SITE_pcornet.ndc_concepts;
drop table SITE_pcornet.ob_smoking;
drop table SITE_pcornet.ob_tobacco;
drop table SITE_pcornet.ob_tobacco_type;
drop table SITE_pcornet.ob_tobacco_data;
drop table SITE_pcornet.rxnorm_ndc_crosswalk;
drop table SITE_pcornet.vital_extract;
drop table SITE_pcornet.vital_transform;
drop table SITE_pcornet.dis_disposition;
drop table SITE_pcornet.encounter_extract;
drop table SITE_pcornet.encounter_transform;
drop table SITE_pcornet.lab_measurements;
drop table SITE_pcornet.ms_ht;
drop table SITE_pcornet.rx_dose_form_data;
drop table SITE_pcornet.specimen_values;
drop table SITE_pcornet.visit_payer;
drop table SITE_pcornet.drg_value;
commit;